version: '3.7'

networks:
    app-tier:
        driver: bridge

services:
    nodejs-api:
        container_name: api
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: on-failure
        ports:
            - "5000:5000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - app-tier
        stdin_open: true
        tty: true
        command: npm start